import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('await page.goto('await page.goto('https://www.way2automation.com/way2auto_jquery/index.php');
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').press('F15');
  await page.locator('input[name="name"]').fill('ttestest');
  await page.locator('input[name="name"]').fill('ttestest');');
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('test');
  await page.locator('input[name="phone"]').click();
  await page.locator('input[name="phone"]').fill('test');
  await page.locator('input[name="email"]').click();
  await page.locator('input[name="email"]').fill('test');
  await page.getByRole('combobox').selectOption('Guatemala');
  await page.locator('input[name="city"]').click();
  await page.locator('input[name="city"]').fill('test');
  await page.locator('#load_box input[name="username"]').click();
  await page.locator('#load_box input[name="username"]').fill('test');
  await page.locator('#load_box input[name="password"]').click();
  await page.locator('#load_box input[name="password"]').fill('test');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.locator('input[name="email"]').fill('testàd');
  await page.locator('input[name="email"]').fill('testàd');');
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').fill('est');
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('input[name="phone"]').click();
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('input[name="phone"]').press('F15');
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('input[name="email"]').fill('test@te.rer');
  await page.locator('input[name="name"]').press('Tab');
  await page.getByRole('combobox').selectOption('Guinea-Bissau');
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('input[name="city"]').click();
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('input[name="city"]').fill('fefef');
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('#load_box input[name="username"]').click();
  await page.locator('input[name="name"]').press('Tab');
  await page.locator('#load_box input[name="username"]').fill('feffe');
  await page.locator('#load_box input[name="password"]').click();
  await page.locator('#load_box input[name="password"]').fill('dfgfcx');
  await page.getByRole('button', { name: 'Submit' }).click();
});